//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20191129061_Ibrahim_Boyaci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gruplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gruplar()
        {
            this.Grup_Kayit = new HashSet<Grup_Kayit>();
            this.Grup_Mesaj = new HashSet<Grup_Mesaj>();
        }
    
        public string grupId { get; set; }
        public string grupAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grup_Kayit> Grup_Kayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grup_Mesaj> Grup_Mesaj { get; set; }
    }
}
