//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20191129061_Ibrahim_Boyaci.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mesajDBEntities1 : DbContext
    {
        public mesajDBEntities1()
            : base("name=mesajDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grup_Kayit> Grup_Kayit { get; set; }
        public virtual DbSet<Grup_Mesaj> Grup_Mesaj { get; set; }
        public virtual DbSet<Gruplar> Gruplar { get; set; }
        public virtual DbSet<Mesajlar> Mesajlar { get; set; }
        public virtual DbSet<Toplu> Toplu { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
    }
}
