//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20191129061_Ibrahim_Boyaci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toplu
    {
        public string tMesajId { get; set; }
        public string tGonderenId { get; set; }
        public string tAlicilarId { get; set; }
        public string tMesaj { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
        public virtual Uyeler Uyeler1 { get; set; }
    }
}
